# MythicTotem by @PQguanfang
#
# READ THE WIKI: mythictotem.superiormc.cn

# Totem Configs
totems:
  test:
    mode: 'VERTICAL'
    layout:
      - 'AAA'
      - 'BBB'
      - 'CCC'
    explains:
      A: 'minecraft:stone'
      B: 'minecraft:end_stone'
      C: 'minecraft:netherrack'
    actions:
      - 'message: Hello!'
      - 'mythicmobs_spawn: SkeletalKnight'
    conditions:
      - 'none'
  test2:
    mode: 'VERTICAL'
    layout:
      - 'AAAAA'
      - 'BBBBB'
      - 'CCCCD'
    explains:
      A: 'minecraft:stone'
      B: 'minecraft:end_stone'
      C: 'minecraft:netherrack'
      D: 'none'
    actions:
      - 'message: Hello!'
      - 'console_command: mm m spawn SkeletalKnight:1 1 %world%, %block_x%, %block_y%, %block_z%'
    conditions:
      - 'world: world'
    disappear: true

  3d-totem:
    mode: 'HORIZONTAL'
    layouts:
      1:
        - 'AAAA'
        - 'BBBB'
        - 'CCCC'
      2:
        - 'CCCC'
        - 'BBBB'
        - 'AAAA'
    explains:
      A: 'minecraft:stone'
      B: 'minecraft:dirt'
      C: 'minecraft:netherrack'
    actions:
      - 'message: Hello World!'
      - 'mythicmobs_spawn: SkeletalKnight'
    conditions:
      - 'none'
    disappear: true

# General Setting Configs
settings:
  debug: false
  # If you are facing double action issue, please bump this value to 20+.
  cooldown-tick: 5
  check-protection:
    can-build: false
    can-break: false
    can-interact: false
    can-use: false
  disappear:
    BukkitAPI:
      # This BukkitAPI option can not be disabled!
      # If you are facing totem blocks not disappear issue, you can try enabled below options.
      # However, they are not fully tested and will lead unknown issues!
      enabled: true
    BlockDamageEvent:
      enabled: false
    BlockBreakEvent:
      enabled: false
  trigger:
    BlockPlaceEvent:
      enabled: true
      require-shift: false
      black-creative-mode: true
    PlayerInteractEvent:
      enabled: false
      require-shift: true
      black-creative-mode: true
    # This event does not support get the player object, so cooldown-tick option does not effect this trigger.
    # And all actions and conditions that related to player is can not be used.
    # And all placeholders that related to player also can not be used.
    # Otherwise you will get tons of errors on console!!!
    BlockRedstoneEvent:
      enabled: true

# Message Configs
messages:
  plugin-reloaded:  "&#98FB98[MythicTotem] &fPlugin reloaded!"
  help-main: |
    &#98FB98&lMythicTotem &7Made by @PQguanfang
    &f/mythictotem help &7- View help.
  help-main-admin: |
    &#98FB98&lMythicTotem &7Made by @PQguanfang
    &f/mythictotem help &7- View help.
    &f/mythictotem list &7- View list of valid totems.
    &f/mythictotem reload &7- Reload the plugin.
    &f/mythictotem save &7- Save your mainhand item.
  help-main-console: |
    &#98FB98&lMythicTotem &7Made by @PQguanfang
    &f/mythictotem help &7- View help.
    &f/mythictotem list &7- View list of valid totems.
    &f/mythictotem reload &7- Reload the plugin.
  list-head: "&#98FB98[MythicTotem] &fValid Totem List:"
  list-prefix: "&f"
  saved: "&#98FB98[MythicTotem] &fSaved your mainhand item!"
  error-args: "&#98FB98[MythicTotem] &cWrong command usage, if you need help, use /mythictotem help!"
  error-miss-permission: "&#98FB98[MythicTotem] &cYou don't have permission to use this command!"
