# Totem Configs
totems:
  test:
    layout:
      - 'AAA'
      - 'BBB'
      - 'CCC'
    explains:
      A: 'minecraft:stone'
      B: 'minecraft:end_stone'
      C: 'minecraft:netherrack'
    actions:
      - 'message: Hello!'
      - 'console_command: mm spawn test %world% %block_x% %block_y% %block_z%'
    conditions:
      - 'world: world'
    disappear: true

    test2:
      layout:
        - 'AAAAA'
        - 'BBBBB'
        - 'CCCCD'
      explains:
        A: 'minecraft:stone'
        B: 'minecraft:end_stone'
        C: 'minecraft:netherrack'
        D: 'none'
      actions:
        - 'message: Hello!'
        - 'console_command: mm m spawn test %world%, %block_x%, %block_y%, %block_z%'
      conditions:
        - 'world: world'
      disappear: true

# General Setting Configs
settings:
  debug: false
  trigger:
    BlockPlaceEvent:
      enabled: true
      require-shift: false
    PlayerInteractEvent:
      enabled: true
      require-shift: true

# Message Configs
messages:
  help-main: |
    &#98FB98&lMythicTotem &7Made by @PQguanfang
    &f/mythictotem help &7- View help.
  help-main-admin: |
    &#98FB98&lMythicTotem &7Made by @PQguanfang
    &f/mythictotem help &7- View help.
    &f/mythictotem list &7- View list of valid totems.
  help-main-console: |
    &#98FB98&lMythicTotem &7Made by @PQguanfang
    &f/mythictotem help &7- View help.
    &f/mythictotem list &7- View list of valid totems.
  list-head: "&#98FB98[MythicTotem] &fValid Totem List:"
  list-prefix: "&f"
  error-args: "&#98FB98[MythicTotem] &cWrong command usage, if you need help, use /mythictotem help!"
  error-miss-permission: "&#98FB98[MythicTotem] &cYou don't have permission to use this command!"
