name: MythicTotem
version: '${project.version}'
main: cn.superiormc.mythictotem.MythicTotem
api-version: 1.13
softdepend:
  - WorldGuard
  - Towny
  - Factions
  - Lands
  - PlotSquared
  - CrashClaim
  - MMOItems
  - MythicLib
  - ItemsAdder
  - Vault
  - PlayerPoints
  - GamePoints
  - Oraxen
  - EcoItems
  - EcoArmor
  - PlaceholderAPI
  - UltraEconomy
  - CoinsEngine
  - RedisEconomy
  - EcoBits
  - MythicMobs

commands:
  mythictotem:
    aliases:
      - "mt"
      - "totem"
    usage: "/mythictotem"
    description: "MythicTotem Main Command."
