name: Maven Build
on:
  workflow_dispatch:  
    inputs:  
      logLevel:  
        description: 'Log level'  
        required: true  
        default: 'warning'
  push:  
    branches: [ "*" ]  
  pull_request:  
    branches: [ "*" ] 
jobs:
  build:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v4
      with:
        repository: "GaLaXyILY/MythicTotem"
        ref: ''
    - name: Set up JDK
      uses: actions/setup-java@v4.2.1
      with:
        java-version: "21"
        distribution: "temurin"
        cache: maven
    - name: Build with Maven
      run: |
        mvn clean package -DskipTests
      env:
        MAVEN_OPTS: "-Xmx2048m --illegal-access=permit"
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: MythicTotem
        path: target/*.jar
